// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cncqxbhjhfotbrvhtplq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuY3F4YmhqaGZvdGJydmh0cGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MTM3MjEsImV4cCI6MjA1NjI4OTcyMX0.UsB8hbNw5RzzJkTlMVuviAy_uMW7Qym4VBsMx_hUtK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);